Added EmailModel
tmthrgd/shoco pull request #2
Opened 2018-06-25 10:17 UTC by richp10

This is a new model trained on roughly 2k varied email addresses.  Initial testing suggests good compression of *short* lists of email addresses.

2018-06-25 11:24 UTC, tmthrgd requested changes

2018-06-25 11:24 UTC, tmthrgd commented on shoco_model_emails.go
> +var EmailModel = &shoco.Model{
You'll need to remove the `shoco` package name to include this file in the package itself, otherwise you get an import cycle. That's what's causing the Travis failure. This file is correct if you included it externally though.

2018-06-25 11:24 UTC, tmthrgd commented on shoco_model_emails.go
> +	Packs: []shoco.Pack{
Ditto here, drop the `shoco` package name.

2018-06-25 11:24 UTC, tmthrgd commented on shoco_model_emails.go
> +import "github.com/tmthrgd/shoco"
This `import` statement isn't needed and causes an import cycle.

2018-06-25 11:41 UTC, tmthrgd requested changes
You'll also need to add the model to the `testModels` variable in shoco_test.go.

2018-06-25 11:43 UTC, richp10 commented on shoco_model_emails.go
> +var EmailModel = &shoco.Model{
Okay - will do.. will sort out all these suggestions tomorrow..

2018-07-02 09:19 UTC, richp10 commented
I think the updated PR fixes the issues you mentioned..

2018-07-04 02:10 UTC, closed without merging

2018-07-04 02:15 UTC, tmthrgd commented
Merged in 7c08ad61c1c1f8536ab990a1f22602782a292b47. (I absent-mindedly forgot to change the git author, sorry about that).